#!/usr/bin/env bash
set -e
[[ $# = 1 ]] || { simplecoin coin --help >&2; exit 1; }

if [[ $1 = @* || ${#1} -ge 40 ]]; then
  coin=$1
else
  coin=$(seth call @simplecoin_factory "coins(uint256)(address)" "$1")
fi

if [[ $coin = 0000000000000000000000000000000000000000 ]]; then
  echo >&2 "${0##*/}: error: no such simplecoin: $1"
  exit 1
fi

feedbase=$(seth call "$coin" "feedbase()(address)")
rules=$(seth call "$coin" "rules()(bytes32)")
rules=$(seth --to-ascii <<<"$rules" | tr -d '\0')
types=$(seth call "$coin" "nextType()(uint48)" | seth --to-dec)
owner=$(seth call "$coin" "owner()(address)")
supply=$(token supply "$coin")

properties=(
  owner
  feedbase
  rules
  supply
  types
)

for name in "${properties[@]}"; do
  printf "%-15s\t%s\n" "$name" "${!name}"
done
