#!/usr/bin/env bash
set -e
count=$(seth call @simplecoin_factory "count()(uint)")
count=$(seth --to-dec "$count")

format="%5s  %8s  %-32s  %24s\n"
printf "$format" COIN OWNER RULES SUPPLY

display-coin() {
  fields=$(simplecoin info "$1")
  owner=$(seth --field owner <<<"$fields")
  rules=$(seth --field rules <<<"$fields")
  supply=$(seth --field supply <<<"$fields")
  printf "$format" "$1" "${owner:0:8}" "$rules" "$supply"
}

for id in $(seq "$count"); do
  display-coin "$((id - 1))" &
done | sort -n
